

import { GlassSidebar } from "@/app/components/shared/sidebar";
import type { Metadata } from "next";
import { SidebarProvider, SidebarInset, SidebarTrigger } from "@/components/ui/sidebar"

import { Button } from "@/components/ui/button"
import DashboardPage from "./page";
export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-500/20 via-blue-500/20 to-pink-500/20">
      <SidebarProvider>
        <GlassSidebar />
        <SidebarInset className="bg-transparent">
          <header className="sticky top-0 z-10 flex h-16 items-center gap-4 border-b border-white/10 bg-background/30 backdrop-blur-md backdrop-filter px-4">
            <SidebarTrigger className="text-foreground" />
            <h1 className="text-xl font-semibold">Glass UI Dashboard</h1>
          </header>
          <main className="p-6">
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          <DashboardPage></DashboardPage>
            </div>
          </main>
        </SidebarInset>
      </SidebarProvider>
    </div>
  );
}